### ISSUE TITLE
Test Run fails

### ISSUE THREAD

**Issue by NICKVALENTINO** [james-stevens/pyrar#40]
Hello!

I seem to be running into the same issue on each of my attempts to install this, and am subsequently stuck on Test Run.  I would greatly appreciate any advice.  

> root@vps:/opt/config# /opt/pyrar/INSTALL_ON_UBUNTU_SERVER/run_pyrar
> Traceback (most recent call last):
>   File "/opt/pyrar/python/bin/policy_subst.py", line 27, in <module>
>     content = template.render(**merge_data)
>   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
>     self.environment.handle_exception()
>   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
>     raise rewrite_traceback_stack(source=source)
>   File "/opt/pyrar/policy_subst/pdns.conf", line 40, in top-level template code
>     gmysql-host={{logins.pdns.server}}
>   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 474, in getattr
>     return getattr(obj, attribute)
> jinja2.exceptions.UndefinedError: 'None' has no attribute 'pdns'
> /usr/local/bin/run_init: .: line 18: can't open '/run/policy_subst/env.inc': **No such file or directory**

### For reference: 

> root@vps:/opt/config# lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.10
> Release:	22.10
> Codename:	kinetic

I was thinking maybe Docker isn't set up correctly, but I have this:

> root@vps:/opt/config# sudo docker run hello-world
> 
> Hello from Docker!
> This message shows that your installation appears to be working correctly.
> To generate this message, Docker took the following steps:
>  1. The Docker client contacted the Docker daemon.
>  2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
>     (amd64)
>  3. The Docker daemon created a new container from that image which runs the
>     executable that produces the output you are currently reading.
>  4. The Docker daemon streamed that output to the Docker client, which sent it
>     to your terminal.
> 
> To try something more ambitious, you can run an Ubuntu container with:
>  $ docker run -it ubuntu bash
> 
> Share images, automate workflows, and more with a free Docker ID:
>  https://hub.docker.com/
> 
> For more examples and ideas, visit:
>  https://docs.docker.com/get-started/

and

> root@vps:/run# docker image ls
> REPOSITORY           TAG       IMAGE ID       CREATED        SIZE
> jamesstevens/pyrar   latest    71b930cd2418   13 hours ago   164MB
> hello-world          latest    9c7a54a9a43c   7 weeks ago    13.3kB

Something is definitely missing, I'm just unsure of what.  

Thank you in advance!

EDIT: I guess there's a bad link somewhere to the **/policy_subst/** directory for env.inc?

**Comment by james-stevens** [comment]
> EDIT: I guess there's a bad link somewhere to the /policy_subst/ directory for env.inc?

That directory has files that need various `config` values substituted into them - therefore, the problem is probably in one of your `config` files. Most likely invalid JSON. I will add validating the JSON to the install guide !!!

Using `jq` check all your config files are valid JSON, e.g. `jq < logins.json` - this will either output your JSON in colour & formatted, or it will give you an error. My guess is your `logins.json` is invalid

> I was thinking maybe Docker isn't set up correctly, but I have this:

It's not that - you can get docker's "hello-world" to run, so it must be set up correctly.

> File "/opt/pyrar/policy_subst/pdns.conf", line 40, in top-level template code
> gmysql-host={{logins.pdns.server}}

The error mentions the `logins` - this is why I think the problem is in there.

**Comment by NICKVALENTINO** [comment]
> Using jq check all your config files are valid JSON, e.g. jq < logins.json - this will either output your JSON in colour & formatted, or it will give you an error. My guess is your logins.json is invalid

Spot on.  I guess I wasn't paying attention when I used a strong password generator that contained a \ and causing an invalid escape. 🤦‍♂️

It runs now, but seems like a boatload of errors that I'll have to look into tomorrow.

Thanks for the help. :)

**Comment by james-stevens** [comment]
No worries - I will add checking the JSON to the instruction :)

**Comment by james-stevens** [comment]
I just noticed there's a bug in the `run_pyrar` script, the line

        -p 127.0.0.1:53:53/udp -p 127.0.0.1:53:53 \

should read

        -p 53:53/udp -p 53:53 \

without this change, external access to the DNS will not be possible
