### ISSUE TITLE
bind address conflict

### ISSUE THREAD

**Issue by NICKVALENTINO** [james-stevens/pyrar#46]
Did a fresh install of everything today:

> root@vps:/opt/config# lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.04.2 LTS
> Release:	22.04
> Codename:	jammy

And attempted to do some workarounds before posting this, but am at a standstill with this issue:

> root@vps:/opt/config# /opt/pyrar/INSTALL_ON_UBUNTU_SERVER/run_pyrar
> docker: Error response from daemon: driver failed programming external connectivity on endpoint cool_lehmann (c4393953f2933b527f91c223a60475be8278b5d7f37c991820b6d5898af81e65): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use.

Confirming that resolver is the conflict:

> root@vps:~# sudo ss -tulwnp | grep :53
> udp   UNCONN 0      0               127.0.0.54:53        0.0.0.0:*    users:(("systemd-resolve",pid=2374,fd=15))                                  
> udp   UNCONN 0      0            127.0.0.53%lo:53        0.0.0.0:*    users:(("systemd-resolve",pid=2374,fd=13))                                  
> tcp   LISTEN 0      4096         127.0.0.53%lo:53        0.0.0.0:*    users:(("systemd-resolve",pid=2374,fd=14))                                  
> tcp   LISTEN 0      4096            127.0.0.54:53        0.0.0.0:*    users:(("systemd-resolve",pid=2374,fd=16))         

Will disable it and see what happens: 

> root@vps:~# sudo rm /etc/resolv.conf
> root@vps:~# sudo touch /etc/resolv.conf
> root@vps:~# sudo systemctl restart docker
> root@vps:~# /opt/pyrar/INSTALL_ON_UBUNTU_SERVER/run_pyrar

After about 60 seconds has passed, I finally get some output and see a lot of reloading along with some errors.  

> chown: /usr/share/doc/postfix/readme: No such file or directory
> Jun 24 22:52:16 ab16b506a356 syslogd 1.5.1: restart (remote reception).
> Jun 24 22:52:16 ab16b506a356 init: starting pid 88, tty '': '/usr/local/bin/start_pdns' 
> Jun 24 22:52:16 ab16b506a356 init: starting pid 89, tty '': '/usr/local/bin/start_nginx' 
> Jun 24 22:52:16 ab16b506a356 init: starting pid 92, tty '': '/usr/local/bin/start_backend_runner' 
> Jun 24 22:52:16 ab16b506a356 init: starting pid 96, tty '': '/usr/local/bin/start_cardproc' 
> Jun 24 22:52:16 ab16b506a356 su: + pts/0 root:daemon 
> Jun 24 22:52:16 ab16b506a356 init: starting pid 100, tty '': '/usr/local/bin/start_spooler' 
> Jun 24 22:52:16 ab16b506a356 pdns: Jun 24 22:52:16 Loading '/usr/lib/pdns/pdns/libgmysqlbackend.so' 
> Jun 24 22:52:16 ab16b506a356 pdns[90]: Loading '/usr/lib/pdns/pdns/libgmysqlbackend.so' 
> Jun 24 22:52:16 ab16b506a356 init: starting pid 103, tty '': '/usr/sbin/crond -f -c /etc/crontabs -l 9' 
> Jun 24 22:52:16 ab16b506a356 pdns: Jun 24 22:52:16 This is a standalone pdns 
> Jun 24 22:52:16 ab16b506a356 pdns[90]: This is a standalone pdns 
> Jun 24 22:52:16 ab16b506a356 pdns: Jun 24 22:52:16 Created local state directory '/var/run/pdns/' 
> Jun 24 22:52:16 ab16b506a356 pdns[90]: Created local state directory '/var/run/pdns/' 
> Jun 24 22:52:16 ab16b506a356 pdns: Jun 24 22:52:16 Listening on controlsocket in '/var/run/pdns/pdns.controlsocket' 
> Jun 24 22:52:16 ab16b506a356 pdns[90]: Listening on controlsocket in '/var/run/pdns/pdns.controlsocket' 
> Jun 24 22:52:16 ab16b506a356 init: starting pid 107, tty '': '/usr/sbin/postfix start-fg >/tmp/postfix.log 2>&1' 
> Jun 24 22:52:16 ab16b506a356 pdns: Jun 24 22:52:16 UDP server bound to 0.0.0.0:5353 
> Jun 24 22:52:16 ab16b506a356 pdns[90]: UDP server bound to 0.0.0.0:5353 
> Jun 24 22:52:16 ab16b506a356 pdns: Jun 24 22:52:16 TCP server bound to 0.0.0.0:5353 
> Jun 24 22:52:16 ab16b506a356 pdns[90]: TCP server bound to 0.0.0.0:5353 
> Jun 24 22:52:16 ab16b506a356 pdns: Jun 24 22:52:16 PowerDNS Authoritative Server 4.6.2 (C) 2001-2022 PowerDNS.COM BV 
> Jun 24 22:52:16 ab16b506a356 pdns[90]: PowerDNS Authoritative Server 4.6.2 (C) 2001-2022 PowerDNS.COM BV 
> Jun 24 22:52:16 ab16b506a356 pdns: Jun 24 22:52:16 Using 64-bits mode. Built using gcc 11.2.1 20220219 on May 13 2022 11:37:19 by buildozer@build-3-16-x86_64. 
> Jun 24 22:52:16 ab16b506a356 pdns[90]: Using 64-bits mode. Built using gcc 11.2.1 20220219 on May 13 2022 11:37:19 by buildozer@build-3-16-x86_64. 
> Jun 24 22:52:16 ab16b506a356 pdns: Jun 24 22:52:16 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2. 
> Jun 24 22:52:16 ab16b506a356 pdns[90]: PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2. 
> Jun 24 22:52:16 ab16b506a356 pdns: Jun 24 22:52:16 [webserver] Listening for HTTP requests on 0.0.0.0:8081 
> Jun 24 22:52:16 ab16b506a356 pdns[90]: [webserver] Listening for HTTP requests on 0.0.0.0:8081 
> Jun 24 22:52:16 ab16b506a356 pdns: Jun 24 22:52:16 Creating backend connection for TCP 
> Jun 24 22:52:16 ab16b506a356 pdns[90]: Creating backend connection for TCP 
> Jun 24 22:52:16 ab16b506a356 pdns: Jun 24 22:52:16 About to create 3 backend threads for UDP 
> Jun 24 22:52:16 ab16b506a356 pdns[90]: About to create 3 backend threads for UDP 
> Jun 24 22:52:16 ab16b506a356 sqlsh: [fileloader:54/check_for_new] -> Reloading file '/opt/pyrar/config/policy.json' 
> Jun 24 22:52:16 ab16b506a356 sqlsh: [fileloader:54/check_for_new] -> Reloading file '/opt/pyrar/config/logins.json' 
> Jun 24 22:52:16 ab16b506a356 sqlsh: [sqlsh:19/<module>] -> Reloading file '/opt/pyrar/config/logins.json' 
> Jun 24 22:52:17 ab16b506a356 run_cardproc.py: [fileloader:54/check_for_new] -> Reloading file '/opt/pyrar/config/policy.json' 
> Jun 24 22:52:17 ab16b506a356 run_cardproc.py: [fileloader:54/check_for_new] -> Reloading file '/opt/pyrar/config/logins.json' 
> Jun 24 22:52:17 ab16b506a356 pdns[90]: Done launching threads, ready to distribute questions 
> Jun 24 22:52:17 ab16b506a356 pdns: Jun 24 22:52:17 Done launching threads, ready to distribute questions 
> Jun 24 22:52:17 ab16b506a356 run_cardproc.py[101]: [fileloader:54/check_for_new] -> Reloading file '/opt/pyrar/config/logins.json' 
> Jun 24 22:52:17 ab16b506a356 run_cardproc.py[101]: [fileloader:54/check_for_new] -> Reloading file '/opt/pyrar/config/registry.json' 
> Jun 24 22:52:17 ab16b506a356 run_cardproc.py[101]: [fileloader:54/check_for_new] -> Reloading file '/opt/pyrar/config/priority.json' 
> Jun 24 22:52:17 ab16b506a356 run_cardproc.py[101]: [run_cardproc:54/run_server] PAY-ENGINE RUNNING 
> Jun 24 22:52:17 ab16b506a356 admin_ui: [2023-06-24 22:52:17 +0000] [86] [INFO] Starting gunicorn 20.0.4 
> Jun 24 22:52:17 localhost gunicorn.wsgi.error: [86] Starting gunicorn 20.0.4
> Jun 24 22:52:17 ab16b506a356 admin_ui: [2023-06-24 22:52:17 +0000] [86] [INFO] Listening at: unix:/run/wsgi_admin.sock (86) 
> Jun 24 22:52:17 localhost gunicorn.wsgi.error: [86] Listening at: unix:/run/wsgi_admin.sock (86)
> Jun 24 22:52:17 ab16b506a356 admin_ui: [2023-06-24 22:52:17 +0000] [86] [INFO] Using worker: sync 
> Jun 24 22:52:17 localhost gunicorn.wsgi.error: [86] Using worker: sync
> Jun 24 22:52:17 ab16b506a356 admin_ui: [2023-06-24 22:52:17 +0000] [157] [INFO] Booting worker with pid: 157 
> Jun 24 22:52:17 localhost gunicorn.wsgi.error: [157] Booting worker with pid: 157
> Jun 24 22:52:17 ab16b506a356 run_spooler.py: [fileloader:54/check_for_new] -> Reloading file '/opt/pyrar/config/policy.json' 
> Jun 24 22:52:17 ab16b506a356 run_spooler.py: [fileloader:54/check_for_new] -> Reloading file '/opt/pyrar/config/logins.json' 

> Jun 24 22:52:19 ab16b506a356 epprest_namereg:     raise ValueError(f"Registry '{this_reg}' not in '{static.LOGINS_FILE}'") 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg: ValueError: Registry 'namereg' not in '/opt/pyrar/config/logins.json' 
> Jun 24 22:52:19 localhost gunicorn.wsgi.error: [192] Exception in worker process Traceback (most recent call last):   File "/usr/lib/python3.10/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker     worker.init_process()   File "/usr/lib/python3.10/site-packages/gunicorn/workers/base.py", line 119, in init_process     self.load_wsgi()   File "/usr/lib/python3.10/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi     self.wsgi = self.app.wsgi()   File "/usr/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi     self.callable = self.load()   File "/usr/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 49, in load     return self.load_wsgiapp()   File "/usr/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp     return util.import_app(self.app_uri)   File "/usr/lib/python3.10/site-packages/gunicorn/util.py", line 358, in import_app     mod = importlib.import_module(module)   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module  
> Jun 24 22:52:19 ab16b506a356 epprest_namereg: [2023-06-24 22:52:19 +0000] [192] [INFO] Worker exiting (pid: 192) 
> Jun 24 22:52:19 localhost gunicorn.wsgi.error: [192] Worker exiting (pid: 192)
> Jun 24 22:52:19 localhost gunicorn.wsgi.error: [195] Exception in worker process Traceback (most recent call last):   File "/usr/lib/python3.10/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker     worker.init_process()   File "/usr/lib/python3.10/site-packages/gunicorn/workers/base.py", line 119, in init_process     self.load_wsgi()   File "/usr/lib/python3.10/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi     self.wsgi = self.app.wsgi()   File "/usr/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi     self.callable = self.load()   File "/usr/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 49, in load     return self.load_wsgiapp()   File "/usr/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp     return util.import_app(self.app_uri)   File "/usr/lib/python3.10/site-packages/gunicorn/util.py", line 358, in import_app     mod = importlib.import_module(module)   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module  
> Jun 24 22:52:19 localhost gunicorn.wsgi.error: [195] Worker exiting (pid: 195)
> Jun 24 22:52:19 ab16b506a356 epprest_namereg: [2023-06-24 22:52:19 +0000] [195] [ERROR] Exception in worker process 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg: Traceback (most recent call last): 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "/usr/lib/python3.10/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:     worker.init_process() 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "/usr/lib/python3.10/site-packages/gunicorn/workers/base.py", line 119, in init_process 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:     self.load_wsgi() 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "/usr/lib/python3.10/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:     self.wsgi = self.app.wsgi() 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "/usr/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:     self.callable = self.load() 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "/usr/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 49, in load 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:     return self.load_wsgiapp() 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "/usr/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:     return util.import_app(self.app_uri) 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "/usr/lib/python3.10/site-packages/gunicorn/util.py", line 358, in import_app 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:     mod = importlib.import_module(module) 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:     return _bootstrap._gcd_import(name[level:], package, level) 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed 
> Jun 24 22:52:19 ab16b506a356 epprest_namereg:   File "/opt/pyrar/python/epprest/wsgi.py", line 5, in <module> 
> 

Appreciate any input.  Also, thanks for adding the random password generator automatically.  Makes things simple. :)

**Comment by james-stevens** [comment]
> Confirming that resolver is the conflict:

Yes this is your issue. This line, in `run_pyrar`, says to listen on all IP addresses for port 53

    -p 53:53/udp -p 53:53 \

You can fix the conflict by changing this to only listen on your server's IP Address, e.g. if your server's IP Address is `64.65.67.68` then change the line to

    -p 64.65.67.68:53:53/udp -p 64.65.67.68:53:53 \

Disabling the resolver is a bad idea :) - it will cause all sorts of problems, so could be the cause of all the other issues !!! 

I'll have to fix this in the instructions

**Comment by james-stevens** [comment]
I've updated the install - look for references to `external_ip.inc` in the section called `Now the rest`

You need to `pull` the latest repo, copy that file (as instructed) & edit it, then recopy the new `run_pyrar` into `/usr/local/bin`

**Comment by james-stevens** [comment]
just had to update the `run_pyrar` script so the `dig @127.0.0.1` test still works :)

**Comment by NICKVALENTINO** [comment]
As expected, the upddate solved the bind issue.
